# Generated by Django 3.1.4 on 2021-01-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santorini', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='com_property',
            new_name='Propertree',
        ),
    ]
